#!/bin/bash

### BEGIN INIT INFO
# Provides:          usbip-Server
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       P5Software USB IP Server
### END INIT INFO

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------
P5SoftwareHome=/etc/P5Software/Linux-Tools
scripthome=$P5SoftwareHome/usbip

# Must be a valid filename
NAME=usbip-Server
PIDFILE=/var/run/$NAME.pid

# Read the configuration file
source $scripthome/$NAME.conf

#This is the command to be run, give the full pathname
PATH=/usr/sbin
EXECUTABLE=usbipd
DAEMON=$PATH/$EXECUTABLE

DAEMON_OPTS="-D"
BIND_OPTS="usbip bind -b $busID"
UNBIND_OPTS="usbip unbind -b $busID"

export PATH="/usr/sbin:/sbin:/usr/bin:/bin"

case "$1" in


# ------------------------------------------------------------
# Start
# ------------------------------------------------------------
start)
if [ -f $PIDFILE ]; then
echo 'Service already running.'
exit 100
fi

#Set the environment appropriately
echo "Setting modprobe usbip-core..."
modprobe usbip-core
echo "Modprobe set."
echo "Setting modprobe usbip-host..."
modprobe usbip-host
echo "Modprobe set."

echo "Starting service..."
start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS -f
echo "Service started."

echo "Binding device..."
$BIND_OPTS
echo "Bind complete."
;;


# ------------------------------------------------------------
# Stop
# ------------------------------------------------------------
stop)
if [ ! -f $PIDFILE ] || ! kill -0 $(cat $PIDFILE); then
echo 'Service not running.'
exit 1
fi

#Unbind the device
echo "Unbinding device..."
$UNBIND_OPTS
echo "Unbind complete."

#Stop the service
echo "Stopping service..."
start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
echo "Service stopped."

;;


# ------------------------------------------------------------
# Status
# ------------------------------------------------------------
status)
status_of_proc -p $PIDFILE $PATH $EXECUTABLE && exit 0 || exit $?
;;


# ------------------------------------------------------------
# Uninstall
# ------------------------------------------------------------
uninstall)
echo "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
local SURE
read SURE
if [ "$SURE" = "yes" ]; then
stop
rm -f "$PIDFILE"
update-rc.d -f usbip-Server remove
rm -fv "$0"
fi
;;


# ------------------------------------------------------------
# Undefined
# ------------------------------------------------------------
*)
echo "Usage: "$1" {start|stop|status|uninstall}"
exit 1
esac

exit 0