#!/bin/bash

### BEGIN INIT INFO
# Provides:          usbip-Client
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       P5Software USB IP Client
### END INIT INFO

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------
P5SoftwareHome=/etc/P5Software/Linux-Tools
scripthome=$P5SoftwareHome/usbip

# Must be a valid filename
NAME=usbip-Client
PIDFILE=/var/run/$NAME.pid

# Read the configuration file
source $scripthome/$NAME.conf

#This is the command to be run, give the full pathname
PATH=/usr/bin
EXECUTABLE=usbip
DAEMON=$PATH/$EXECUTABLE

DAEMON_OPTS="attach -r $serverFQDN -b $busID"
DETACH_OPTS="detach -p 0"

export PATH="/usr/sbin:/sbin:/usr/bin:/bin"

case "$1" in


# ------------------------------------------------------------
# Start
# ------------------------------------------------------------
start)
if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
echo 'Service already running.'
exit 100
fi

#Set the environment appropriately
echo "Setting modprobe vhci-hcd..."
modprobe vhci-hcd
echo "Modprobe set."

echo "Starting service..."
start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
echo "" > $PIDFILE
echo "Service started."
;;


# ------------------------------------------------------------
# Stop
# ------------------------------------------------------------
stop)
if [ ! -f $PIDFILE ]; then
echo 'Service not running.'
exit 1
fi

#Detach the device
echo "Detaching device..."

$DAEMON $DETACH_OPTS

echo "Device detached."

#Stop the service
echo "Stopping service..."
echo "Ignoring that there is no pid in the pid file; Expected behavior."
start-stop-daemon --stop --oknodo --pidfile $PIDFILE
echo "Service stopped."


rm -r $PIDFILE
;;


# ------------------------------------------------------------
# Status
# ------------------------------------------------------------
status)
status_of_proc -p $PIDFILE $PATH $EXECUTABLE && exit 0 || exit $?
;;


# ------------------------------------------------------------
# Uninstall
# ------------------------------------------------------------
uninstall)
if [ -f $PIDFILE ]; then
echo 'You must stop the service before you can uninstall it.'
exit 1
fi

echo "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
read SURE
if [ "$SURE" = "yes" ]; then
update-rc.d -f $NAME remove
rm -fv "$0"
fi
;;


# ------------------------------------------------------------
# Undefined
# ------------------------------------------------------------
*)
echo "Usage: "$1" {start|stop|status|uninstall}"
exit 1
esac

exit 0